[tool.poetry]
name = "loadenv"
version = "0.0.1"
description = "Environment loading tool."
readme = "README.md"
documentation = "http://localhost:8080/LoadEnv/doc/index.html"
repository = "https://github.com/sandialabs/LoadEnv"
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: DevOps',
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3 :: Only',
]
packages = [
    { include = 'loadenv' }
]
include = [ "CHANGELOG.md" ]


[tool.poetry.dependencies]
python = "^3.6"
setenvironment = {git = "https://github.com/sandialabs/SetEnvironment.git", rev = "master"}
determinesystem = {git = "https://github.com/sandialabs/DetermineSystem.git", rev = "master"}
keywordparser = {git = "https://github.com/sandialabs/KeywordParser.git", rev = "master"}


[tool.poetry.dev-dependencies]
mock = "^4.0.3"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
Sphinx = "^3.5.1"
sphinx-argparse = "^0.2.5"
sphinx-rtd-theme = "^0.5.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
